routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get("/members","HomeController@members");
Route::get("/videos", "VideoController@index");
Route::get("/video/{id}", "VideoController@show");
Route::get("search", "SearchController@search");
Route::post("vote", "ThreadController@vote");

Route::get("/create/thread", "ThreadController@create");
Route::post("/create/thread", "ThreadController@store");
Route::get("/edit/thread/{thread}", "ThreadController@edit");
Route::post("/edit/thread/{thread}", "ThreadController@update");

Route::get("/create/post", "PostController@create");
Route::post("/create/post", "PostController@store");
Route::get("/edit/post/{post}", "PostController@edit");
Route::post("/edit/post/{post}", "PostController@update");

Route::post("create/comment/{post}", 'PostController@addComment');
Route::post("create/answer/{thread}", 'ThreadController@addAnswer');
Route::post("accept/{answer}", 'ThreadController@acceptAnswer');
Route::post("reject/{answer}", 'ThreadController@rejectAnswer');
Route::post("create/reply/{answer}", 'ThreadController@addReply');

Route::get('/edit/{table}/{id}','Admin\ModelController@edit');
Route::post('/edit/{table}/{id}','Admin\ModelController@update');
Route::get('/create/{table}','Admin\ModelController@create');
Route::post('/create/{table}','Admin\ModelController@store');
Route::get('/post/{id}/{slug?}','PostController@show');
Route::get('/posts/{category?}','PostController@index');
Route::get('/threads/{channel?}','ThreadController@index');
Route::get('/thread/{id}/{slug?}','ThreadController@show');

app/Models/Forum/Thread.php
<?php

namespace App\Models\Forum;

use App\Models\User;
use Conner\Tagging\Taggable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

/**
 * @property Collection answers
 * @property int author_id
 * @property string title
 * @property string body
 * @property string channel
 * @property int id
 * @property string tags
 * @property User author
 * @method static create(array $data)
 * @method static findOrFail($id)
 * @method static published()
 */
class Thread extends Model
{
    use Taggable;

    protected $fillable = ["title", "body", "channel", "author_id"];

    public function author()
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function cnl()
    {
        return $this->belongsTo(Channel::class, 'channel');
    }

    public function votes()
    {
        return $this->hasMany(Vote::class, 'thread_id');
    }

    public function upvotes()
    {
        return $this->votes()->where('is_upvote', 1);
    }

    public function downvotes()
    {
        return $this->votes()->where('is_upvote', 0);
    }

    public function scopePublished(Builder $query)
    {
        return $query->where('published', 1);
    }

    public function getTagsAttribute($tags)
    {
        return $tags;
    }

    public function getTagsArrayAttribute()
    {
        if (empty($this->tags)) {
            return collect();
        }
        return collect(explode(',', $this->tags));
    }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Forum\Answer;
use App\Models\Forum\Channel;
use App\Models\Forum\Thread;
use App\Models\Forum\Vote;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ThreadController extends Controller
{
    public function index($channel = null)
    {
        $tag = false;
        /** @var Builder $query */
        $query = Thread::published();
        if ($channel !== null) {
            if (starts_with($channel, "tag:")) {
                $tag = str_after($channel, "tag:");
            } else {
                $channel = Channel::where("channel", $channel)->first();
                if ($channel !== null) {
                    $query->where("channel", $channel->channel);
                }
            }
        }
        if ($tag) {
            $query->where("tags", "like", "%$tag%");
        }
        $threads = $query->withCount([
            'answers',
            'answers as accepted_answer' => function (Builder $query) {
                $query->where('accepted', 1);
            }
        ])->latest('updated_at')->paginate();
        $channels = Channel::all();
        $tags = Thread::existingTags()->pluck('name');
        $alert = !!$tag || !!$channel;

        return view('thread/index', compact('threads', 'channels', "tags", "alert", "channel", "tag"));
    }

    public function show($id)
    {
        /** @var Thread $thread */
        $thread = Thread::findOrFail($id);
        $exists = Storage::exists("public/users/{$thread->author->id}");
        if ($exists) {
            $thread->author->image = "/storage/users/" . $thread->author->id;
        } else {
            $thread->author->image = "/storage/users/default.png";
        }

        $thread->load(['answers.user', 'answers.replies.user']);
        $hasAccepted = $thread->answers->contains(function ($answer) {
            return $answer->accepted;
        });
        foreach ($thread->answers as $answer) {
            $exists = Storage::exists("public/users/{$answer->user->id}");
            if ($exists) {
                $answer->user->image = "/storage/users/" . $answer->user->id;
            } else {
                $answer->user->image = "/storage/users/default.png";
            }

            foreach ($answer->replies as $reply) {
                $exists = Storage::exists("public/users/{$reply->user->id}");
                if ($exists) {
                    $reply->user->image = "/storage/users/" . $reply->user->id;
                } else {
                    $reply->user->image = "/storage/users/default.png";
                }
            }
        }
        $isOwnPost = false;
        $loggedUser = null;
        if (Auth::check()) {
            /** @var User $loggedUser */
            $loggedUser = Auth::user();
            if ($loggedUser->id === $thread->author->id or $loggedUser->role == 'admin') {
                $isOwnPost = true;
            }

            $exists = Storage::exists("public/users/{$loggedUser->id}");
            if ($exists) {
                $loggedUser->image = "/storage/users/" . $loggedUser->id;
            } else {
                $loggedUser->image = "/storage/users/default.png";
            }
        }

        $data = compact("thread", "isOwnPost", "loggedUser", "hasAccepted");
        return view('thread/show', $data);
    }

    public function create()
    {
        if(!Auth::check()){
            abort(401);
        }

        $channels = Channel::all();
        $title = ["key" => "title", "value" => null, "type" => "text"];
        $body = ["key" => "body", "value" => null];
        $associatedChannels = ["multi" => false, "key" => "channel", "name" => "channel", "options" => $channels,
            "values" => collect([])];
        $url = "create/thread";
        $isCreation = true;

        $tags = Thread::existingTags()->pluck('name');
        $existingTags = ["key" => "tags", "value" => null, "type" => "text"];

        $data = compact(
            "title", "body", "associatedChannels",
            "url", "isCreation", "tags", "existingTags"
        );
        return view(
            "thread.create",
            $data
        );
    }

    /**
     * @param Request $request
     * @return RedirectResponse|Redirector
     */
    public function store(Request $request)
    {
        if (!Auth::check()) {
            abort(401);
        }

        $this->validate($request, [
            "title" => "required",
            "body" => "required",
            "channel" => "required|exists:channels,channel",
        ]);

        $data = $request->only(["title", "body", "channel"]);
        $data["author_id"] = Auth::user()->id;
        /** @var Thread $thread */
        $thread = Thread::create($data);
        if ($request->get("tags")) {
            $thread->tag(explode(',', $request->get("tags")));
        }
        $thread->save();

        return redirect("thread/$thread->id");
    }

    public function edit(Thread $thread)
    {
        if (is_null($user = Auth::user())) {
            abort(401);
        }

        if ($thread->author_id !== $user->id && !$user->isAdmin()) {
            abort(401);
        }

        $channels = Channel::all();
        $title = ["key" => "title", "value" => $thread->title, "type" => "text"];
        $body = ["key" => "body", "value" => $thread->body];
        $associatedChannels = ["multi" => false, "key" => "channel", "name" => "channel", "options" => $channels,
            "values" => collect([$thread->channel])];
        $url = "edit/thread/$thread->id";
        $isCreation = false;

        $tags = Thread::existingTags()->pluck('name');
        $existingTags = ["key" => "tags", "value" => $thread->tags, "type" => "text"];

        $data = compact(
            "title", "body", "associatedChannels",
            "url", "isCreation", "tags", "existingTags"
        );
        return view(
            "thread.create",
            $data
        );
    }

    public function update(Thread $thread, Request $request)
    {
        if (is_null($user = Auth::user())) {
            abort(401);
        }

        if ($thread->author_id !== $user->id && !$user->isAdmin()) {
            abort(401);
        }

        $this->validate($request, [
            "title" => "required",
            "body" => "required",
            "channel" => "required|exists:channels,channel",
        ]);

        $data = $request->only(["title", "body", "channel"]);
        $data["author_id"] = Auth::user()->id;
        /** @var Thread $thread */
        $thread = $thread->fill($data);
        if ($request->get("tags")) {
            $thread->tag(explode(',', $request->get("tags")));
        }
        $thread->save();

        return redirect("thread/$thread->id");
    }

    public function addAnswer(Thread $thread, Request $request)
    {
        if (!($user = Auth::user())) {
            throw new NotFoundHttpException();
        }

        $answerId = $thread->answers()->insertGetId([
            "answer" => $request->get("answer"),
            "user_id" => $user->id,
            "thread_id" => $thread->id,
        ]);

        return $answerId;
    }

    public function addReply(Answer $answer, Request $request)
    {
        if (!($user = Auth::user())) {
            throw new NotFoundHttpException();
        }

        $replyId = $answer->replies()->insertGetId([
            "reply" => $request->get("reply"),
            "user_id" => $user->id,
            "answer_id" => $answer->id,
        ]);

        return $replyId;
    }

    public function acceptAnswer(Answer $answer)
    {
        if (!($user = Auth::user())) {
            throw new NotFoundHttpException();
        }
        $thread = $answer->thread;
        if ($user->id !== $thread->author_id) {
            throw new NotFoundHttpException();
        }

        $hasAccepted = !! $thread->answers()->where("accepted", 1)->count();

        if($hasAccepted) {
            return ["accepted" => false];
        }

        $answer->accepted = 1;
        $answer->save();
        return ["accepted" => true];
    }

    public function rejectAnswer(Answer $answer)
    {
        if (!($user = Auth::user())) {
            throw new NotFoundHttpException();
        }
        $thread = $answer->thread;
        if ($user->id !== $thread->author_id) {
            throw new NotFoundHttpException();
        }

        $answer->accepted = 0;
        $answer->save();
        return ["rejected" => true];
    }

    public function vote(Request $request)
    {
        if (!($user = Auth::user())) {
            throw new NotFoundHttpException();
        }

        $this->validate($request, [
            "thread_id" => "required",
            "is_upvote" => "required",
        ]);

        $vote = Vote::where("user_id", $user->id)
            ->where("thread_id", $request->get("thread_id"))
            ->first();
        if ($vote) {
            return ["created" => false, "is_upvote" => $vote->is_upvote];
        }

        $attributes = [
            "user_id" => $user->id,
            "thread_id" => $request->get("thread_id"),
            "is_upvote" => $request->get("is_upvote"),
        ];
        Vote::create($attributes);
        return ["created" => true];
    }
}

resources/views/thread/index.blade.php
@extends('layouts.app')

@section("style")
    <style>
        .post-preview {
            width: 100%;
        }
    </style>
@endsection

@section("style")
    <style>
        .post-preview {
            padding: 1.5rem;
        }

        a:hover{
            text-decoration: none; !important;
        }

        .label {
            font-size: small;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <h2 class="text-primary"><strong>CLUSTERed Forum</strong></h2>
        <hr class="primary">
        @if ($alert)
            <div class="alert alert-info lead">
                Showing threads
                @if (isset($channel))
                    published in <strong>{{$channel}}</strong>
                @endif {{-- IF channel --}}
            </div>
        @endif
        <div class="row">
            <section class="col-md-8">
                @forelse($threads as $thread)
                    <a href="{{url("/thread/$thread->id")}}">
                        <div class="post-preview">
                            <div class="text-container">
                                <h4 class="strong-primary">{{$thread->title}}</h4>
                                {{substr(strip_tags($thread->body), 0, 200)}}... <br>
                            </div>
                            <div class="image-container lead">
                                <div>
                                    @if($thread->answers_count)
                                        <span class="label label-primary">
                                            {{$thread->answers_count}} answers
                                        </span>
                                    @else
                                        <span class="label label-default">
                                            unanswered
                                        </span>
                                    @endif</div>

                                <div style="margin-top: 1rem;">
                                    @if($thread->accepted_answer)
                                        <span class="label label-success">solved</span>
                                    @else
                                        <span class="label label-warning">unsolved</span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </a>
                @empty
                    No thread available
                @endforelse

                {{$threads->links()}}

            </section>
            <section class="col-md-4">
                @if(Auth::check())
                    <div class="post-info col-md-12">
                        <a class="btn btn-primary" href="{{url("/create/thread")}}">Create New</a>
                    </div>
                @endif

                <div class="post-info col-md-12">
                    <h3>Channel</h3>
                    <ul>
                        @foreach($channels as $channel)
                            <li>
                                <a href="{{url("threads/$channel->channel")}}">
                                    {{$channel->channel}}
                                </a>
                            </li>
                        @endforeach
                    </ul>
                </div>

                <div class="post-info col-md-12">
                    <h3>Tags</h3>

                    @foreach($tags as $tag)

                        <a href="{{url("threads/tag:$tag")}}">
                            <span class="label label-info">{{$tag}}</span>
                        </a>

                    @endforeach

                </div>

            </section>
        </div>
    </div>
@endsection

resources/views/thread/show.blade.php
@extends('layouts.app')

@section("style")
    <style>
        .comment {
            width: 100%;
        }
    </style>
@endsection

@section('content')
    <div class="container" v-cloak id="vm" xmlns:v-bind="http://www.w3.org/1999/xhtml" xmlns:v-on="http://www.w3.org/1999/xhtml">
        <div class="row">
            <div class="col-md-6 col-md-offset-1">
                <h2 class="text-center"> {{$thread->title}}
                    <span class="lead label label-success" v-if="hasAccepted">Solved</span>
                </h2>
            </div>
        </div>
        <section class="row">

            <div class="col-md-6 col-md-offset-1">
                <div class="post-body">{!! nl2br($thread->body) !!}</div>

                @if($thread->tags_array->count() > 0)
                    <hr class="primary">
                    <strong class="text-info">Tags</strong>:
                    @foreach($thread->tags_array as $tag)
                        <span class="label label-primary">{{$tag}}</span>
                    @endforeach
                @endif
            </div>

            <div class="post-sidebar col-md-4">
                @if($isOwnPost)
                    <div class="post-info">
                        <a class="btn btn-primary" href="{{url("edit/thread/$thread->id")}}">Edit Thread</a>
                    </div>
                @else
                    <div class="post-info">
                        <button type="button" class="btn btn-primary" v-on:click="upvote">
                            Upvote
                            <span class="badge">@{{upvotes}}</span>
                        </button>
                        <button type="button" class="btn btn-warning pull-right" v-on:click="downvote">
                            Downvote
                            <span class="badge">@{{downvotes}}</span>
                        </button>
                    </div>
                @endif
                <div class="post-info">
                    <span class="strong-primary">Author:</span>
                    <a href="{{url("user/".$thread->author->id)}}">
                        {{$thread->author->name}}
                    </a>

                </div>
                @if(!empty($thread->channel))
                    <div class="post-info">
                        <span class="strong-primary">Channel:</span>
                        <a href="{{url("threads/{$thread->channel}")}}">
                            {{$thread->channel}}
                        </a>
                    </div>
                @endif

                @if(!empty($thread->updated_at))
                    <div class="post-info">
                        Published
                        <strong>{{$thread->updated_at->diffForHumans()}}</strong>
                    </div>
                @endif


            </div>


        </section>

        <section class="row">
            <div class="col-md-8 col-md-offset-2" v-show="answers.length">
                <h2 class="text-primary">Answers</h2>
                <hr class="primary">

                <div class="comment" v-for="(answer, i) in answers">
                    <div v-bind:class="{'bg-info': answer.accepted}"
                         v-bind:style="{fontWeight: (answer.accepted? 'bold': 'medium')}">
                        <div class="image-container">
                            <a :href="'{{url("user") . "/"}}' + answer.user.id">
                                <img :src="answer.user.image" :alt="answer.user.name" :title="answer.user.name"
                                     class="img img-responsive">
                            </a>
                        </div>
                        <div class="text-container">
                            <div class="col-md-12">
                                <a :href="'{{url("user") . "/"}}' + answer.user.id">
                                    <strong>@{{answer.user.name}}</strong>
                                </a>
                                <span v-html="answer.answer"></span>
                            </div>
                            <div class="col-md-12" v-if="answer.accepted">
                                <button class="btn btn-warning" v-on:click="reject(answer.id, i)">Reject</button>
                            </div>
                            <div class="col-md-12" v-if="isOwnPost && !hasAccepted">
                                <button class="btn btn-success" v-on:click="accept(answer.id, i)">Accept</button>
                            </div>

                        </div>
                    </div>
                    <hr class="" style="border-top-width: 2px">
                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-2">
                            <div class="comment" v-for="reply in answer.replies">
                                <a :href="'{{url("user") . "/"}}' + reply.user.id">
                                    <strong>@{{reply.user.name}}</strong>
                                </a>
                                <span v-html="reply.reply"></span>
                            </div>
                            <div class="form-horizontal">
                                <h3 class="text-left">Reply To This Answer</h3>
                                <div class="form-group">
                                    <label :for="answer.id"></label>
                                    <div class="col-md-12">
                                        <textarea :id="answer.id" class="form-control"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <button class="btn btn-info" v-on:click="addReply(answer.id, i)">
                                            Reply
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

            <div class="col-md-8 col-md-offset-2">
                <h3>Add Answer</h3>
                <div class="form-group">
                    <label for="answer" class="sr-only">
                        Answer
                    </label>

                    <textarea name="answer" id="answer" class="form-control"></textarea>

                </div>
                <div class="form-group">

                    <button type="button" class="btn bg-primary" v-on:click="addAnswer">Answer</button>

                </div>
            </div>
        </section>
    </div>
@endsection

@section("script")
    <script>
        new Vue({
            el: '#vm',
            data: {
                answers: {!! $thread->answers !!},
                upvotes: {{$thread->upvotes->count()}},
                downvotes: {{$thread->downvotes->count()}},
                isLoggedIn: {!! $loggedUser? 1: 0 !!},
                isOwnPost: {!! $isOwnPost? 1: 0 !!},
                hasAccepted: {!! $hasAccepted? 1: 0 !!}
            },
            methods: {
                addAnswer: function () {
                    const data = {answer: tinyMCE.activeEditor.getContent()};
                    axios.post('{{url("create/answer/$thread->id")}}', data)
                        .then(response => {
                            this.answers.splice(this.answers.length, 0, {
                                answer: data.answer,
                                user: {
                                    name: '{{$loggedUser}}',
                                    image: '{{optional($loggedUser)->image}}'
                                }
                                }
                            )
                        })
                },
                accept: function(answer_id, i) {
                    axios.post("{{url("accept")}}/" + answer_id)
                        .then(response => {
                            if (response.data.accepted) {
                                this.hasAccepted = true;

                                const ans = this.answers[i];
                                ans.accepted = true;
                            }
                        })
                },
                reject: function(answer_id, i) {
                    axios.post("{{url("reject")}}/" + answer_id)
                        .then(response => {
                            if (response.data.rejected) {
                                this.hasAccepted = false;

                                const ans = this.answers[i];
                                ans.accepted = false;
                            }
                        })
                },
                addReply: function (answer_id, i) {
                    const data = {
                        reply: $('#' + answer_id).val()
                    };
                    axios.post("{{url("create/reply")}}/" + answer_id, data)
                        .then(response => {
                            const ans = this.answers[i];
                            ans.replies.splice(ans.replies.length, 0, {
                                reply: data.reply,
                                id: response.data.id,
                                user: {
                                    name: '{{$loggedUser}}',
                                    image: '{{optional($loggedUser)->image}}'
                                }
                            })
                        })
                },
                upvote: function () {
                    this.vote(true)
                },
                downvote: function () {
                    this.vote(false)
                },
                vote: function (is_upvote) {
                    const data = {
                        is_upvote,
                        thread_id: '{{$thread->id}}'
                    };
                    axios.post("{{url("vote")}}", data)
                        .then(response => {
                            if (response.data.created) {
                                if (data.is_upvote) {
                                    this.upvotes++;
                                } else {
                                    this.downvotes++;
                                }
                            } else {
                                if (data.is_upvote) {
                                    window.alert("You have already upvoted.");
                                } else {
                                    window.alert("You have already downvoted.");
                                }
                            }
                        })
                }
            }
        })
    </script>

    <script src="{{asset("/js/tinymce/tinymce.min.js")}}"></script>

    <script>
        tinymce.init({
            selector: '#answer',
            height: 200,
            plugins: [
                'advlist autolink lists link image charmap print preview anchor textcolor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste code help wordcount'
            ],
            toolbar: 'undo redo |  formatselect | bold italic underline backcolor | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent | removeformat | help',
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css'
            ],
            setup: function (editor) {
                editor.on('load', function () {
                    $('.mce-branding').remove();
                })
            }
        });
    </script>
@endsection